{{- if .Values.persistence.pdName -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pdName }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "teleport.fullname" . }}-storage
  gcePersistentDisk:
    pdName: {{ .Values.persistence.pdName }}
    fsType: {{ .Values.persistence.fsType }}
{{- end }}
